### ISSUE TITLE
Replace sync crossbeam-channels

### ISSUE THREAD

**Issue by samuel-rufi** [Alex6323/netzwerk#3]
In future, once available, replace sync crossbeam-channels with async channels to use all the advantages of an async architecture.

`async_std::sync::channel` is still in development (unstable), progress should be followed:
https://docs.rs/async-std/1.5.0/async_std/sync/fn.channel.html

**Comment by Alex6323** [comment]
This lib now uses mpsc channels from futures crate. Those can be used together with async_std. Wherever mpmc is needed I solved that through bundling of several mpsc channels.
