### ISSUE TITLE
Removement of task::sleep()

### ISSUE THREAD

**Issue by samuel-rufi** [Alex6323/netzwerk#4]
Make sure if the different `task::sleep()` are really necessary and if there might be cases where it doesn´t work as expected. Ideally it could be removed.

**Comment by Alex6323** [comment]
Those were mostly included initially to simulate something is happening ;). With many fundamental things now implemented, there is only one instance in the lib, where this is still necessary. And that is for the auto-reconnect feature, where upon unintentional loss of connection, the system tries to automatically reconnect to a peer after a certain delay.
