### ISSUE TITLE
Review use of select macro

### ISSUE THREAD

**Issue by samuel-rufi** [Alex6323/netzwerk#6]
Review use of select macro to avoid messages getting lost. Events get selected similar to following:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8f3d1b0d1d8ebfca73f42e8230e7e93a

it should print foo and bar since both receivers should received data.

**Comment by Alex6323** [comment]
yup. Due to the switch to mpsc from the futures crate, this is no issue anymore. Hence this can be closed.
